export const FEEDS: { name: string; url: string }[] = [
  { name: "TechCrunch AI", url: "https://techcrunch.com/category/artificial-intelligence/feed/" },
  { name: "The Verge AI", url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml" },
  { name: "Ars Technica AI", url: "https://arstechnica.com/ai/feed/" },
  { name: "VentureBeat AI", url: "https://venturebeat.com/category/ai/feed/" },
  { name: "MIT Technology Review", url: "https://www.technologyreview.com/feed/" },
  { name: "OpenAI Blog", url: "https://openai.com/blog/rss.xml" },
  { name: "Google DeepMind", url: "https://deepmind.google/blog/rss.xml" },
  { name: "Hugging Face Blog", url: "https://huggingface.co/blog/feed.xml" },
  { name: "Hacker News (AI)", url: "https://hnrss.org/newest?q=AI+OR+LLM+OR+GPT+OR+Claude&points=100" },
];

// Constrained tag vocabulary — keeps tagging consistent across runs.
// Claude is told to ONLY use tags from these lists.
export const TAG_VOCAB = {
  category: [
    "research",
    "product-launch",
    "funding",
    "policy",
    "safety",
    "open-source",
    "benchmarks",
    "infrastructure",
    "incident",
    "opinion",
  ],
  domain: [
    "llm",
    "image-generation",
    "video-generation",
    "audio",
    "robotics",
    "coding",
    "agents",
    "search",
    "healthcare",
    "education",
    "enterprise",
    "consumer",
    "hardware",
    "chips",
  ],
  company: [
    "openai",
    "anthropic",
    "google",
    "deepmind",
    "meta",
    "microsoft",
    "nvidia",
    "amazon",
    "apple",
    "xai",
    "mistral",
    "cohere",
    "huggingface",
    "perplexity",
    "stability",
    "midjourney",
    "other",
  ],
  model: [
    "gpt",
    "claude",
    "gemini",
    "llama",
    "mistral",
    "grok",
    "dall-e",
    "sora",
    "stable-diffusion",
    "midjourney",
    "veo",
    "other",
    "none",
  ],
} as const;
